Add domain to WebMock allowed list
Without this, the stub_request in process_job_test was causing it to
fail because the return values are not usable in the processing code,
it fails, and causes the job to fail instead of finish.

I was also getting:

```
Step::PreprocessesControllerTest#test_should_create_a_preprocess:
RuntimeError: Neutered Exception WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: GET https://core.dev.collectionspace.org/cspace-services/personauthorities?pgNum=0&pgSz=1&wf_deleted=false with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'Basic YWRtaW5AY29yZS5jb2xsZWN0aW9uc3BhY2Uub3JnOkFkbWluaXN0cmF0b3I=', 'User-Agent'=>'Ruby'}

You can stub this request with the following snippet:

stub_request(:get, "https://core.dev.collectionspace.org/cspace-services/personauthorities?pgNum=0&pgSz=1&wf_deleted=false").
  with(
    headers: {
	  'Accept'=>'*/*',
	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
	  'Authorization'=>'Basic YWRtaW5AY29yZS5jb2xsZWN0aW9uc3BhY2Uub3JnOkFkbWluaXN0cmF0b3I=',
	  'User-Agent'=>'Ruby'
    }).
  to_return(status: 200, body: "", headers: {})

============================================================
    app/models/batch.rb:71:in `handler'
    app/jobs/preprocess_job.rb:18:in `perform'
    test/controllers/step/preprocesses_controller_test.rb:38:in `block
    in <class:PreprocessesControllerTest>'
```

This request is actually being made when handler initialization calls
Collectionspace::Client.domain to set the domain to be used at various
points in the mapping process.

I considered stubbing handler but it does seem like maybe there are
benefits to actually calling the thing and making sure it doesn't fall
over at some point in the tests.